### ISSUE TITLE
Adding transform on route in code gives Null Reference Exception when not defining empty transform first

### ISSUE THREAD

**Issue by PieterBoeren** [microsoft/reverse-proxy#517]
### Describe the bug
Adding transform on route in code gives Null Reference Exception when not defining an empty transform first. The code below (other route properties left out for clarity) gives a null reference exception since the "Transforms" property is not initialized. A workaround is to specify the an empty List (uncomment the line in the code below).

### To Reproduce

```
var route = new ProxyRoute()
{
    RouteId = "route1",
    // Transforms = new List<IDictionary<string, string>>(),
};
route.AddTransformPathPrefix("/");
```

### Further technical details

- Latest preview
- .Net 5

**Comment by Tratcher** [comment]
Good find, those extensions need to initialize the list if it's null. Interested in sending a PR?

**Comment by PieterBoeren** [comment]
I can try, but not until Tuesday. Can this be solved by just creating the empty list in the constructor of the ProxyRoute class, that would be way simpler then solving it in all extension methods...

**Comment by Tratcher** [comment]
That would be easier, but it's still not foolproof so long as Transforms can be set back to null like it would here:
https://github.com/microsoft/reverse-proxy/blob/3832fd34bb9bdfb25fb299767420939096a590a3/src/ReverseProxy/Configuration/ConfigurationConfigProvider.cs#L169
